name: Create Docker Image Manifest

on:
  push:
    branches:
      - main
    paths:
      - 'RELEASE'
      - 'VERSION'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  create-manifest:
    needs: [build-and-push-amd64, build-and-push-arm64]
    runs-on: ubuntu-latest

    steps:
    - name: Read version from RELEASE file
      id: get_version
      run: echo "VERSION=$(cat RELEASE)" >> $GITHUB_ENV
      
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Create and push multi-arch manifest
      run: |
        docker manifest create imashen/zerotier-aio:release-${{ env.VERSION }} \
          imashen/zerotier-aio:amd64 \
          imashen/zerotier-aio:arm64
        docker manifest push --purge imashen/zerotier-aio:release-${{ env.VERSION }}